services:
  dataspawner1:
    image: camunda/data-spawner
    environment:
      - ZEEBE_JOB_TYPE=serviceTask1 ## io.camunda.zeebe:userTask
      - JOBTIME_MIN=0 ## value in miliseconds
      - JOBTIME_MAX=500
      - ZEEBE_ADDRESS=${ZEEBE_ADDRESS}
      - CAMUNDA_OAUTH_URL=${CAMUNDA_OAUTH_URL}
      - ZEEBE_CLIENT_ID=${ZEEBE_CLIENT_ID}
      - ZEEBE_CLIENT_SECRET=${ZEEBE_CLIENT_SECRET}
      - ZEEBE_AUTHORIZATION_SERVER_URL=${CAMUNDA_OAUTH_URL}
      - ZEEBE_REST_ADDRESS=${ZEEBE_REST_ADDRESS}
      - ZEEBE_GRPC_ADDRESS=${ZEEBE_GRPC_ADDRESS}
      - ZEEBE_TOKEN_AUDIENCE=zeebe.camunda.io
      - ZEEBE_CLIENT_CLOUD_CLUSTERID=${ZEEBE_CLUSTER_ID}
      - ZEEBE_CLIENT_CLOUD_CLIENTID=${ZEEBE_CLIENT_ID}
      - ZEEBE_CLIENT_CLOUD_CLIENTSECRET=${ZEEBE_CLIENT_SECRET}
      - ZEEBE_CLIENT_CLOUD_AUTHURL=${ZEEBE_AUTHORIZATION_SERVER_URL}
    deploy:
      replicas: 2

  dataspawner2:
    image: camunda/data-spawner
    environment:
      - ZEEBE_JOB_TYPE=io.camunda.zeebe:userTask ## io.camunda.zeebe:userTask
      - JOBTIME_MIN=10000 ## value in miliseconds
      - JOBTIME_MAX=50000
      - ZEEBE_ADDRESS=${ZEEBE_ADDRESS}
      - CAMUNDA_OAUTH_URL=${CAMUNDA_OAUTH_URL}
      - ZEEBE_CLIENT_ID=${ZEEBE_CLIENT_ID}
      - ZEEBE_CLIENT_SECRET=${ZEEBE_CLIENT_SECRET}
      - ZEEBE_AUTHORIZATION_SERVER_URL=${CAMUNDA_OAUTH_URL}
      - ZEEBE_REST_ADDRESS=${ZEEBE_REST_ADDRESS}
      - ZEEBE_GRPC_ADDRESS=${ZEEBE_GRPC_ADDRESS}
      - ZEEBE_TOKEN_AUDIENCE=zeebe.camunda.io
      - ZEEBE_CLIENT_CLOUD_CLUSTERID=${ZEEBE_CLUSTER_ID}
      - ZEEBE_CLIENT_CLOUD_CLIENTID=${ZEEBE_CLIENT_ID}
      - ZEEBE_CLIENT_CLOUD_CLIENTSECRET=${ZEEBE_CLIENT_SECRET}
      - ZEEBE_CLIENT_CLOUD_AUTHURL=${ZEEBE_AUTHORIZATION_SERVER_URL}
    deploy:
      replicas: 10

networks:
  default:
